### ISSUE TITLE
Only 10 levels are supported at most

### ISSUE THREAD

**Issue by mnlin0905** [aleen42/gitbook-mindmaps#1]
When I try to load more than 10 levels of structure, like

```mind:height=300
* 1
  * 2
    * 3
      * 4
        * 5
          * 6
            * 7
              * 8
                * 9
                  * 10
                    * 11
```

It can't draw the required graph correctly

![image](https://user-images.githubusercontent.com/17874282/117957826-0274e100-b34d-11eb-9e91-b776e243115f.png)

**Without "11"**

So, what should I do?

**Comment by aleen42** [comment]
@mnlin0905 I'll check it later, and it seems like the problem of `markmap`.

**Comment by mnlin0905** [comment]
@aleen42 ok, thanks

**Comment by mnlin0905** [comment]
@aleen42 
Is this phenomenon similar https://github.com/gera2ld/markmap/issues/47

**Comment by mnlin0905** [comment]
@aleen42
I tried to modify the place where "new remarkable()" appears in plugin, and changed it to:

```js
new Remarkable({
  maxNesting: Infinity
});
```

The problem has been solved

**Comment by aleen42** [comment]
The author of [dundalek/markmap](https://github.com/dundalek/markmap) seems to have already archived the project and do not maintained it anymore. You can try to open an issue for this problem, and I'll find a time to try to migrate from it to [gera2ld/markmap](https://github/gera2ld/markmap). The fastest solution is to maintain it myself.

@mnlin0905 try the latest released version 1.1.0.

**Comment by mnlin0905** [comment]
@aleen42 thanks

**Comment by mnlin0905** [comment]
![image](https://user-images.githubusercontent.com/17874282/118469672-81e12680-b738-11eb-9e45-3070a26afe23.png)

@aleen42  hi, 
Can the version of `nodejs` be updated?
I'm currently using `12.16.2`

**Comment by aleen42** [comment]
The specifications have no impacts and I can run it under Node 13.x
